#!/bin/bash

BINTRAY_JSON="$(dirname $(readlink -f $0))/../build/bintray.json"
GIT_REVISION="$(git describe --tags --always --dirty)"

BINTRAY_SUBJECT="${BINTRAY_SUBJECT:-bigbrotherteam}"
BINTRAY_REPO="${BINTRAY_REPO:-BigBrother}"
BINTRAY_PACKAGE="${BINTRAY_PACKAGE:-BigBrother}"
BINTRAY_FLAVOR=""

if [[ $TRAVIS_BRANCH != master ]]; then
	BINTRAY_FLAVOR="-${TRAVIS_BRANCH}"
fi

tee "${BINTRAY_JSON}" <<EOF
{
  "package": {
    "name": "${BINTRAY_PACKAGE}${BINTRAY_FLAVOR}",
    "repo": "${BINTRAY_REPO}",
    "subject": "${BINTRAY_SUBJECT}",
    "desc": "Allows the connection of Minecraft: Java Edition clients to PocketMine-MP servers. Made for PocketMine-MP",
    "website_url": "https://github.com/BigBrotherTeam/BigBrother",
    "issue_tracker_url": "https://github.com/BigBrotherTeam/BigBrother/issues",
    "vcs_url": "https://github.com/BigBrotherTeam/BigBrother.git",
    "github_use_tag_release_notes": false,
    "licenses": ["LGPL-3.0"],
    "labels": ["pocketmine", "pocketmine-mp", "minecraft", "mcpe-server", "mcpc-server", "php", "php72"],
    "public_download_numbers": true,
    "public_stats": true
  },

  "version": {
    "name": "${GIT_REVISION}"
  },

  "files":
    [
      {"includePattern": "build/BigBrother.phar", "uploadPattern": "${TRAVIS_BRANCH}/BigBrother-${GIT_REVISION}.phar"}
    ],
  "publish": true
}
EOF
