#!/bin/bash

BINTRAY_JSON="$(dirname $(readlink -f $0))/../build/bintray.json"
GIT_REVISION="$(git describe --tags --always --dirty)"
GIT_SHA1="$(git log -1 --format=[%h])"

BINTRAY_SUBJECT="${BINTRAY_SUBJECT:-BigBrotherTeam}"

cat<<EOF >"${BINTRAY_JSON}"
{
  "package": {
    "name": "BigBrother",
    "repo": "Test",
    "subject": "${BINTRAY_SUBJECT}",
    "desc": "Allows the connection of Minecraft: Java Edtion clients to PocketMine-MP servers. Made for PocketMine-MP",
    "website_url": "https://github.com/BigBrotherTeam/BigBrother",
    "issue_tracker_url": "https://github.com/BigBrotherTeam/BigBrother/issues",
    "vcs_url": "https://github.com/BigBrotherTeam/BigBrother.git",
    "github_use_tag_release_notes": false,
    "licenses": ["LGPL-3.0"],
    "labels": ["pocketmine", "pocketmine-mp", "minecraft", "mcpe-server", "mcpc-server", "php", "php72"],
    "public_download_numbers": true,
    "public_stats": true
  },

  "version": {
    "name": "${GIT_REVISION}"
  },

  "files":
    [
      {"includePattern": "build/BigBrother.phar", "uploadPattern": "${TRAVIS_BRANCH}/BigBrother-${GIT_REVISION}${GIT_SHA1}.phar"}
    ],
  "publish": true
}
EOF

cat "${BINTRAY_JSON}"
