#!/usr/bin/env php
<?php
/**
 *  ______  __         ______               __    __
 * |   __ \|__|.-----.|   __ \.----..-----.|  |_ |  |--..-----..----.
 * |   __ <|  ||  _  ||   __ <|   _||  _  ||   _||     ||  -__||   _|
 * |______/|__||___  ||______/|__|  |_____||____||__|__||_____||__|
 *             |_____|
 *
 * BigBrother plugin for PocketMine-MP
 * Copyright (C) 2014-2015 shoghicp <https://github.com/shoghicp/BigBrother>
 * Copyright (C) 2016- BigBrotherTeam
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * @author BigBrotherTeam
 * @link   https://github.com/BigBrotherTeam/BigBrother
 *
 */

define("PROJECT_ROOT", dirname(__FILE__, 2));
define("DEVTOOL_REPO", "pmmp/PocketMine-DevTools");
define("DEVTOOL_FILE", "/dists/DevTools.phar");
define("BIGBROS_FILE", "/dists/BigBrother.phar");

define("GITHUB_API", "https://api.github.com/repos/%s/releases");
define("USER_AGENT", "User-Agent: Mozilla/5.0 like Gecko");

$include_dirs  = ['src', 'resources', 'vendor'];
$include_files = ['LICENSE', 'README.md', 'plugin.yml'];

try {
	if(ini_get("phar.readonly") == 1){
		system(join(' ', array_merge([PHP_BINARY, '-dphar.readonly=0'], $argv)), $retval);
		exit($retval);
	}

	/**
	 * skip if devtools is already downloaded less than 15 min
	 * to avoid reaching github API rate limit
	 */
	if(!file_exists(PROJECT_ROOT . DEVTOOL_FILE) or time() > ($atime = fileatime(PROJECT_ROOT . DEVTOOL_FILE)) +900){
		//query latest devtool release
		$ctx = stream_context_create(["http" => ["header" => "User-Agent: ". USER_AGENT]]);
		$asset = json_decode(@file_get_contents(sprintf(GITHUB_API, DEVTOOL_REPO), false, $ctx))[0]->assets[0];

		//check if devtools is up to date
		if(!isset($atime) or strtotime($asset->updated_at) > $atime){
			@mkdir(dirname(PROJECT_ROOT . DEVTOOL_FILE));
			echo sprintf("Downloding DevTools from '%s'", $asset->browser_download_url) . PHP_EOL;
			@file_put_contents(PROJECT_ROOT . DEVTOOL_FILE, @file_get_contents($asset->browser_download_url));
		}
	}

	$command = join(' ', [
		PHP_BINARY, '-dphar.readonly=0',
		PROJECT_ROOT . DEVTOOL_FILE,
		'--relative', PROJECT_ROOT,
		'--make', join(',', $include_dirs),
		'--out', PROJECT_ROOT . BIGBROS_FILE
	]);

	echo "Running DevTools..." . PHP_EOL;
	echo "$command" . PHP_EOL;
	system($command);

	$phar = new Phar(PROJECT_ROOT . BIGBROS_FILE);
	foreach ($include_files as $file){
		$phar->addFile(PROJECT_ROOT . '/' . $file, $file);
	}
}catch(Exception $e){
	echo "unexpected error has occured!" . PHP_EOL;
	echo $e->getTraceAsString() . PHP_EOL;
	exit(1);
}
