#!/usr/bin/env php
<?php
/**
 *  ______  __         ______               __    __
 * |   __ \|__|.-----.|   __ \.----..-----.|  |_ |  |--..-----..----.
 * |   __ <|  ||  _  ||   __ <|   _||  _  ||   _||     ||  -__||   _|
 * |______/|__||___  ||______/|__|  |_____||____||__|__||_____||__|
 *             |_____|
 *
 * BigBrother plugin for PocketMine-MP
 * Copyright (C) 2014-2015 shoghicp <https://github.com/shoghicp/BigBrother>
 * Copyright (C) 2016- BigBrotherTeam
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * @author BigBrotherTeam
 * @link   https://github.com/BigBrotherTeam/BigBrother
 *
 */
declare(strict_types=1);

namespace pocketmine\utils {
	class Color { /* this is stub */ }
}

namespace {
	/** @noinspection PhpIncludeInspection */
	require_once($source = "src/shoghicp/BigBrother/utils/ColorUtils.php");

	use shoghicp\BigBrother\utils\ColorUtils;

	$output = join(DIRECTORY_SEPARATOR, [dirname(__FILE__, 2), "resources", "color_index.dat"]);
	$force = array_reduce($argv, function($acx, $val) { return $acx || $val == "--force"; }, false);

	if(!is_file($output) || filemtime($output) < filemtime($source) || $force){
		echo "generating color index...".PHP_EOL;
		echo "this may take more than 5min. take a break with a cup of coffee!".PHP_EOL;

		ColorUtils::generateColorIndex($output);

		echo "done.".PHP_EOL;
	}else{
		echo "color index is already up-to-date".PHP_EOL;
	}
}
